"""Backend interfaces (Protocols) for the three storage subsystems.

The app/store.py facade keeps the public API stable and validation/orchestration
in one place; these Protocols define exactly what each backend must implement.

Feature 002 (Art. X) adds User + AuthToken to the registry and threads an
`owner_id` through the course/lecture reads/lists/deletes so the owner filter is
enforced *in the backend*, not only in the route. `owner_id=None` is the internal
/ system path (no owner filter) used by the pipeline and the startup recovery scan.
"""

from __future__ import annotations

from typing import Protocol

from app.models import (AuthToken, Course, DiagramAsset, Lecture, LectureStatus,
                        NoteChunk, TokenKind, User)


class VectorBackend(Protocol):
    def add(self, chunks: list[NoteChunk]) -> None: ...
    def query(
        self,
        course_id: str,
        query_embedding: list[float],
        n: int,
        exclude_lecture_id: str | None,
    ) -> list[dict]: ...
    def list_by_lecture(self, lecture_id: str) -> list[dict]: ...
    def update_text(self, chunk_id: str, text: str, embedding: list[float]) -> None: ...
    def delete_by_lecture(self, lecture_id: str) -> None: ...


class RegistryBackend(Protocol):
    # --- users (002, Art. X) ---
    def create_user(self, user: User) -> User: ...
    def get_user(self, user_id: str) -> dict | None: ...
    def get_user_by_email(self, email: str) -> dict | None: ...
    def get_user_by_google_sub(self, google_sub: str) -> dict | None: ...
    def update_user(self, user_id: str, changes: dict) -> None: ...

    # --- auth tokens: OTP / set-password / reset (002, Art. X) — stored hashed ---
    def create_auth_token(self, token: AuthToken) -> AuthToken: ...
    def find_auth_token(
        self, kind: TokenKind, *, user_id: str | None = None,
        token_hash: str | None = None,
    ) -> dict | None: ...
    def bump_auth_token(
        self, token_id: str, *, attempts: int | None = None, used: bool | None = None,
    ) -> None: ...
    def invalidate_auth_tokens(self, user_id: str, kind: TokenKind) -> None: ...

    # --- courses (owner-scoped when owner_id is given) ---
    def create_course(self, course: Course) -> Course: ...
    def list_courses(self, owner_id: str | None = None) -> list[dict]: ...
    def get_course(self, course_id: str, owner_id: str | None = None) -> dict | None: ...
    def delete_course_row(self, course_id: str, owner_id: str | None = None) -> bool: ...

    # --- lectures (owner-scoped via the parent course when owner_id is given) ---
    def create_lecture(self, lecture: Lecture) -> Lecture: ...
    def get_lecture(self, lecture_id: str, owner_id: str | None = None) -> dict | None: ...
    def list_lectures(self, course_id: str) -> list[dict]: ...
    def list_lecture_ids(self, course_id: str) -> list[str]: ...
    def list_all_lectures(self) -> list[dict]: ...  # system path (startup recovery scan)
    def update_lecture(
        self, lecture_id: str, status: LectureStatus | None, progress: str | None
    ) -> None: ...
    def set_lecture_links(self, lecture_id: str, links: dict) -> None: ...
    def delete_lecture_rows(self, lecture_id: str, owner_id: str | None = None) -> bool: ...

    # --- diagrams ---
    def create_diagram(self, asset: DiagramAsset) -> DiagramAsset: ...
    def get_diagram(self, asset_id: str) -> dict | None: ...
    def list_diagrams(self, lecture_id: str) -> list[dict]: ...
    def list_all_diagrams(self) -> list[dict]: ...


class ObjectBackend(Protocol):
    def save_diagram_image(
        self, lecture_id: str, asset_id: str, ext: str, data: bytes
    ) -> str: ...
    def delete_lecture_assets(self, lecture_id: str) -> None: ...
    def read_diagram_bytes(self, asset: dict) -> bytes | None: ...
