"""Backend interfaces (Protocols) for the three storage subsystems.

The app/store.py facade keeps the public API stable and validation/orchestration
in one place; these Protocols define exactly what each backend must implement.
"""

from __future__ import annotations

from typing import Protocol

from app.models import Course, DiagramAsset, Lecture, LectureStatus, NoteChunk


class VectorBackend(Protocol):
    def add(self, chunks: list[NoteChunk]) -> None: ...
    def query(
        self,
        course_id: str,
        query_embedding: list[float],
        n: int,
        exclude_lecture_id: str | None,
    ) -> list[dict]: ...
    def list_by_lecture(self, lecture_id: str) -> list[dict]: ...
    def update_text(self, chunk_id: str, text: str, embedding: list[float]) -> None: ...
    def delete_by_lecture(self, lecture_id: str) -> None: ...


class RegistryBackend(Protocol):
    def create_course(self, course: Course) -> Course: ...
    def list_courses(self) -> list[dict]: ...
    def get_course(self, course_id: str) -> dict | None: ...
    def create_lecture(self, lecture: Lecture) -> Lecture: ...
    def get_lecture(self, lecture_id: str) -> dict | None: ...
    def list_lectures(self, course_id: str) -> list[dict]: ...
    def list_lecture_ids(self, course_id: str) -> list[str]: ...
    def update_lecture(
        self, lecture_id: str, status: LectureStatus | None, progress: str | None
    ) -> None: ...
    def set_lecture_links(self, lecture_id: str, links: dict) -> None: ...
    def delete_lecture_rows(self, lecture_id: str) -> bool: ...
    def delete_course_row(self, course_id: str) -> bool: ...
    def create_diagram(self, asset: DiagramAsset) -> DiagramAsset: ...
    def get_diagram(self, asset_id: str) -> dict | None: ...
    def list_diagrams(self, lecture_id: str) -> list[dict]: ...
    def list_all_diagrams(self) -> list[dict]: ...


class ObjectBackend(Protocol):
    def save_diagram_image(
        self, lecture_id: str, asset_id: str, ext: str, data: bytes
    ) -> str: ...
    def delete_lecture_assets(self, lecture_id: str) -> None: ...
    def read_diagram_bytes(self, asset: dict) -> bytes | None: ...
