"""Pipeline orchestration (Core merge — tasks T010, T015–T018).

Runs in the background after POST /api/lectures returns 202. Sequence:
transcribe -> extract slides (text + images, filtered) -> align -> merge ->
refine (dedupe + clean explanation) -> place diagrams (T017) -> embed ->
persist per course (T018). Progress is written to the lecture for the polling UI.

Raw audio is deleted the moment transcription finishes, and the entire temp
workspace is removed in `finally` — so no recording ever survives, even on
failure (Constitution Art. IV).
"""

from __future__ import annotations

import shutil
from pathlib import Path

from app import diagrams, refine, retrieve, store
from app.align import align
from app.embed import embed_texts
from app.merge import merge_section
from app.models import DiagramAsset, LectureStatus, NoteChunk, SourceType
from app.slides import extract_slides, filter_images
from app.transcribe import transcribe


def run_pipeline(lecture_id: str, course_id: str, audio_path: str,
                 pdf_path: str, workdir: str) -> None:
    try:
        store.update_lecture(lecture_id, status=LectureStatus.processing,
                             progress="Transcribing audio…")
        segments = transcribe(audio_path)
        _safe_delete(audio_path)  # audio's only job is done — delete now (Art. IV)

        store.update_lecture(lecture_id, progress="Reading slides…")
        sections, images = extract_slides(pdf_path)
        images = filter_images(images, num_pages=len(sections))

        store.update_lecture(lecture_id, progress="Aligning what was said to the slides…")
        aligned = align(sections, segments)

        store.update_lecture(lecture_id, progress="Describing diagrams…")
        diagrams_by_section = _persist_diagrams(lecture_id, sections, images)

        store.update_lecture(lecture_id, progress="Composing your merged notes…")
        chunks = _compose_chunks(lecture_id, course_id, aligned, diagrams_by_section)
        if not chunks:
            raise RuntimeError("No content was produced from the audio + slides.")

        store.update_lecture(lecture_id, progress="Saving notes…")
        for chunk, vector in zip(chunks, embed_texts([c.text for c in chunks])):
            chunk.embedding = vector
        store.add_chunks(chunks)
        _link_prior_lectures(lecture_id, course_id, chunks)

        store.update_lecture(lecture_id, status=LectureStatus.ready, progress="Ready.")
    except Exception as exc:  # surface to the polling UI; never crash the worker
        store.update_lecture(lecture_id, status=LectureStatus.failed,
                             progress=f"Failed: {exc}")
    finally:
        # Guarantee no upload (audio or PDF) survives, even on failure (Art. IV).
        shutil.rmtree(workdir, ignore_errors=True)


def _compose_chunks(lecture_id, course_id, aligned, diagrams_by_section) -> list[NoteChunk]:
    chunks: list[NoteChunk] = []
    order = 0
    for sa in aligned:
        # merge weaves slide + spoken; refine then de-duplicates + cleans the prose
        # into one explanation (provenance preserved, spoken-only still flagged).
        segments = refine.refine_section(sa.section.title, merge_section(sa))
        for b in segments:
            reason = b.reason
            if b.spoken_only:
                reason = "★ Spoken-only (not on the slides) — " + reason
            chunks.append(NoteChunk(
                lecture_id=lecture_id, course_id=course_id, topic=sa.section.title,
                order=order, text=b.text, source_type=SourceType(b.source_type),
                reason=reason, confidence=b.confidence,
            ))
            order += 1
        for asset in diagrams_by_section.get(sa.section.index, []):
            # description (Strong, T030) doubles as the searchable text + caption;
            # falls back to a plain caption when no vision model is available.
            caption = asset.description or f"Diagram from “{sa.section.title}”."
            reason = "Preserved from this slide section (US-3)."
            if asset.description:
                reason += " Description generated by a vision model (US-5)."
            chunks.append(NoteChunk(
                lecture_id=lecture_id, course_id=course_id, topic=sa.section.title,
                order=order, text=caption,
                source_type=SourceType.diagram, reason=reason,
                confidence=1.0, diagram_ref=asset.id,
            ))
            order += 1
    return chunks


def _link_prior_lectures(lecture_id: str, course_id: str, chunks: list[NoteChunk]) -> None:
    """Stretch (T040/T041): link each topic to the most similar earlier lecture.

    Best-effort — linking never fails the pipeline. Uses each topic's combined text to
    find the strongest prior match (capped, similarity-thresholded; Art. VI), excluding
    this lecture so it never links to itself.
    """
    try:
        topic_texts: dict[str, list[str]] = {}
        for c in chunks:
            if c.source_type != SourceType.diagram and c.text.strip():
                topic_texts.setdefault(c.topic, []).append(c.text)
        links = retrieve.find_links(
            course_id,
            [(t, " ".join(v)) for t, v in topic_texts.items()],
            exclude_lecture_id=lecture_id,
        )
        if links:
            store.set_lecture_links(lecture_id, links)
    except Exception:
        pass


def _persist_diagrams(lecture_id, sections, images) -> dict[int, list[DiagramAsset]]:
    out: dict[int, list[DiagramAsset]] = {}
    for im in images:
        topic = sections[im.section_index].title if im.section_index < len(sections) else "Diagram"
        asset = DiagramAsset(lecture_id=lecture_id, image_ref="", section_topic=topic)
        asset.image_ref = store.save_diagram_image(lecture_id, asset.id, im.ext, im.data)
        asset.description = diagrams.describe_image(im.data, im.ext, topic)  # Strong (T030)
        store.create_diagram(asset)
        out.setdefault(im.section_index, []).append(asset)
    return out


def _safe_delete(path: str) -> None:
    try:
        Path(path).unlink(missing_ok=True)
    except OSError:
        pass
